### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by unional** [thanhptr/extts#6]
Are you planning to release this project under MIT or some other licenses?

Thanks.

**Comment by maxtpham** [comment]
I have not mentioned anything regarding licensing, it means no licencing at all. Or if you find any text in my code base or docs that accidentally mentioned about licensing, please let me know to remove it.

So you are all free to use, modify, fork and/or redistribute it :)

I've just seen your Pull request, I will merge it, thanks for your efforts!

**Comment by unional** [comment]
Thanks.

**Comment by fabriciomurta** [comment]
Hello! I believe when you have some time, you'd attach to your project the appropriate license for it:
[Public domain](https://wiki.creativecommons.org/wiki/Public_domain).

It is very nice from you leaving this available for everyone, so I'd like to contribute with this piece of information that might save a potential headache at some point.

Some things like attaching the [jsduck](https://github.com/senchalabs/jsduck) (which [is under GPLv3](https://github.com/senchalabs/jsduck#copying)) could imply specific licenses for specific parts of the code, so maybe a good idea would be to add a README.md on 0.tools directory pointing jsduck's origins as well as license (I believe jsut the two links in this paragraph should do), then on the root of your .cspoj attach the public domain license (I believe a link to the public domain above should do).

Then in the root of the project you create a licenses section stating that parts of the repository are subject to their respective licenses and link to the README.md's in generator/0.tools and generator/c2.tools.ExtTS.

I'm still not sure how to deal with the generated .d.ts, as they can be seen as public domain, but all the comments inside it can be pretty much claimable by ExtJS and licensed under their terms. I hate to say that but the safe approach would be not to keep the output here so everyone generating the .d.ts would (hopefully) have the rights (be it from Sencha commercial or from Sencha GPL products).

But it might be enough just to mention on the main readme files that the generated .d.ts files' licensing follows the ExtJS version used to be generated them. For example, if the .d.ts files you shared here are from ExtJS-gpl, then mention they are licensed under GPLv3. If they come from ExtJS-commercial, then point to the Sencha license bound to this version (a link, maybe?).

I don't think leaving the code with comments would be a problem as Sencha has all the code open on their examples explorers and sencha fiddle (after all, for users to test ExtJS they need the extjs-all.js file). So as long as you are providing something publicly available, you should be good. :)

Ah, for the NuGet packages inside the project you released as public domain, I believe as long as you don't add the nuget packages nor DLLs (as you have done here) you should be fine. As soon as the users grab the project and run nuget restore, they will have any licensing or copyright acknowledgement if they apply. So, no specific licensing mentions necessary for nuget packages is needed -- given you didn't commit them into the repo.
